### ISSUE TITLE
Master is not working with current movim

### ISSUE THREAD

**Issue by kolewu** [movim/movim_docker#11]
Since master uses current movim master but the install script isn't adapted, the movim container fails in initialisation. First with the wrong command `mud.php` that has been merged with `daemon.php` and after fixing this, the missing database migrations ending in the error reported in #9.

**Comment by kawaii** [comment]
Thanks @kolewu, eventually `redux` will become `master` but this should fix any issues with the old Docker image in the meantime. :)
