### ISSUE TITLE
Configuration ENV for mysql support? 

### ISSUE THREAD

**Issue by poVoq** [movim/movim_docker#17]
Is there some way to utilize MySQL with this docker image? I have an external database server that I would like to use, but which has only MySQL installed. Given that this is generally supported by Movim it would be cool if the Docker image would have this option as well.

Thanks!

**Comment by poVoq** [comment]
Seems like @stevenroose did this already in hin own fork:
https://github.com/stevenroose/movim_docker/commit/8ab9082fc3eb81cbfa9e5d6976ced82896072862
Would be nice if this could be pulled back.

**Comment by kawaii** [comment]
@poVoq is there any reason why you can't use a PostgreSQL container? MySQL has _many_ issues why you should probably avoid using it for a production system.

**Comment by poVoq** [comment]
Is there a reason it should not be possible given that Movim has the support build in?

In my specific case I would like to use an external database server that only runs MySQL.
