### ISSUE TITLE
Document root is wrong

### ISSUE THREAD

**Issue by Vertux** [movim/movim_docker#18]
The document root path does not match. The oficial Docker nginx images 
uses `/usr/share/nginx/html` as default, but the movim image and the stack.yaml example use `/var/www/html`.

**Comment by kawaii** [comment]
You aren't supposed to use the example literally, you are supposed to mount your own nginx configuration into the container. See #16 and the answers within for more information.

**Comment by Vertux** [comment]
@kawaii thank you for pointing me in the right direction.
