### ISSUE TITLE
Movim not started

### ISSUE THREAD

**Issue by un4me** [movim/movim_docker#21]
I tried several versions 14 and 15, the result is the same.

Unencrypted 
movim_1       | An error occured, check syslog for more information
movim_1       | 
movim_1       | Warning: file_put_contents(/var/www/html/cache/websocket): failed to open stream: Permission denied in /var/www/html/src/Movim/Daemon/Core.php on line 83
movim_1       | An error occured, check syslog for more information
movim_1       | 
movim_1       |                                                                                
movim_1       |   [RuntimeException]                                                           
movim_1       |   Failed to listen on Unix domain socket "unix:///var/www/html/cache/socketap  
movim_1       |   i.sock": Unknown error                                                       
movim_1       |                                                                                
movim_1       | 
movim_1       | Exception trace:
movim_1       |  () at /var/www/html/vendor/react/socket/src/UnixServer.php:75
movim_1       |  React\Socket\UnixServer->__construct() at /var/www/html/vendor/react/socket/src/Server.php:34
movim_1       |  React\Socket\Server->__construct() at /var/www/html/src/Movim/Console/DaemonCommand.php:108
movim_1       |  Movim\Console\DaemonCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:264
movim_1       |  Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:874
movim_1       |  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:228
movim_1       |  Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:130
movim_1       |  Symfony\Component\Console\Application->run() at /var/www/html/daemon.php:18

What could be the problem?

**Comment by kawaii** [comment]
Restarting the container generally fixes that issue, it's an odd permissions error even though all files are owned by `www-data`.

**Comment by un4me** [comment]
fixed it by changing the rights to the folder cache to 1777

**Comment by un4me** [comment]
> Restarting the container generally fixes that issue, it's an odd permissions error even though all files are owned by `www-data`.

restarting didn't change anything
