### ISSUE TITLE
Switch from Debian to Alpine container base image

### ISSUE THREAD

**Issue by kawaii** [movim/movim_docker#29]
Reminder to myself to refactor the Dockerfile to use an Alpine base image when I have some free time on a rainy day. :umbrella:

**Comment by edhelas** [comment]
:3 ?

**Comment by sando38** [comment]
Hi kawaii,

I have created a Docker image for movim, also refactored it a bit, using php8 as a basis, etc. There is an Alpine and a Debian version:

https://github.com/sando38/movim

The Alpine variant has an issue, it does not show images/ avatars, they apear blank. It seems a dependency or something is missing. The Debian variant works good. 

Maybe this is a starting point for you to refactor. If you think we should included this refactored image into this repo, I would also offer to make a PR.

Have a great day,
sando

**Comment by edhelas** [comment]
If this is not happening and we're happy with `php:8.1-fpm` I'd prefer to close this ticket.
