### ISSUE TITLE
"the requested PHP extension zmq is missing from your system"

### ISSUE THREAD

**Issue by elevatedcode** [movim/movim_docker#6]
At the step when composer is installing the dependencies for movim the following error occurs and the whole process is stopping. 

I have checked the php-cli.ini but there are no entries for extensions. 

Does anyone know something about this problem or does a workaround exist?

> Step 12/16 : RUN curl -sS https://getcomposer.org/installer | php     && php composer.phar install

>  ---> Running in bfacbe5a13fd
> All settings correct for using Composer
> Downloading...
> 
> Composer (version 1.5.2) successfully installed to: /var/www/movim/composer.phar
> Use it: php composer.phar
> 
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for react/zmq dev-master -> satisfiable by react/zmq[dev-master].
>     - react/zmq dev-master requires ext-zmq * -> the requested PHP extension zmq is missing from your system.
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - /etc/php/7.0/cli/php.ini
>     - /etc/php/7.0/cli/conf.d/10-opcache.ini
>     - /etc/php/7.0/cli/conf.d/10-pdo.ini
>     - /etc/php/7.0/cli/conf.d/15-xml.ini
>     - /etc/php/7.0/cli/conf.d/20-calendar.ini
>     - /etc/php/7.0/cli/conf.d/20-ctype.ini
>     - /etc/php/7.0/cli/conf.d/20-curl.ini
>     - /etc/php/7.0/cli/conf.d/20-dom.ini
>     - /etc/php/7.0/cli/conf.d/20-exif.ini
>     - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
>     - /etc/php/7.0/cli/conf.d/20-ftp.ini
>     - /etc/php/7.0/cli/conf.d/20-gd.ini
>     - /etc/php/7.0/cli/conf.d/20-gettext.ini
>     - /etc/php/7.0/cli/conf.d/20-iconv.ini
>     - /etc/php/7.0/cli/conf.d/20-imagick.ini
>     - /etc/php/7.0/cli/conf.d/20-json.ini
>     - /etc/php/7.0/cli/conf.d/20-mbstring.ini
>     - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
>     - /etc/php/7.0/cli/conf.d/20-pdo_pgsql.ini
>     - /etc/php/7.0/cli/conf.d/20-pgsql.ini
>     - /etc/php/7.0/cli/conf.d/20-phar.ini
>     - /etc/php/7.0/cli/conf.d/20-posix.ini
>     - /etc/php/7.0/cli/conf.d/20-readline.ini
>     - /etc/php/7.0/cli/conf.d/20-shmop.ini
>     - /etc/php/7.0/cli/conf.d/20-simplexml.ini
>     - /etc/php/7.0/cli/conf.d/20-sockets.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
>     - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
>     - /etc/php/7.0/cli/conf.d/20-wddx.ini
>     - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
>     - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
>     - /etc/php/7.0/cli/conf.d/20-xsl.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> ERROR: Service 'movim' failed to build: The command '/bin/sh -c curl -sS 

> https://getcomposer.org/installer | php     && php composer.phar install' returned a non-zero code: 2

**Comment by oappiah** [comment]
See this PR : #7

**Comment by kawaii** [comment]
Resolved by #7.
